name: flutter_wall_layout
description: A Layout widget displaying a set of bricks (widgets with different shapes) as a vertical or horizontal list, like a wall...
version: 1.0.0
author: David GONZALEZ (david.gonzalez.freelance@gmail.com)
homepage: https://github.com/GONZALEZD/flutter_wall_layout

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter